### ISSUE TITLE
Check for login information embedded in the code

### ISSUE THREAD

**Issue by mxlian** [schwarzwaldgeier/meteo#2]
1. Scripte ändern, damit diese info weg vom repo liegt
2. Diese login daten ändern

**Comment by sebschmied** [comment]
Habe sämtliche Dateien, die auf die wetter-db zugreifen aus dem Tree entfernt und neu hinzugefügt. Sie holen sich die credentials jetzt aus einer Datei, die in der .gitignore steht.

Das Passwort ist trotzdem zu unsicher und muss noch geändert werden, allerdings müssen wir da erst eventuelle Abhängigkeiten checken.
