### ISSUE TITLE
save original wind speed and original wind direction

### ISSUE THREAD

**Issue by mxlian** [schwarzwaldgeier/meteo#31]
We are saving only the calibrated values, but are we sure there are 100% correct? Specially the wind speed correction with a fixed constant??

**Comment by sebschmied** [comment]
Added original_wind_speed and original_wind_maxspeed columns. (both float). They don't get data yet.

**Comment by sebschmied** [comment]
Also added original_wind_direction (float)

**Comment by sebschmied** [comment]
Added columns to localhost database as well.

**Comment by sebschmied** [comment]
remote schwarzwaldgeier.de database now gets original data, too.
