### ISSUE TITLE
Add forecast to phone message

### ISSUE THREAD

**Issue by sebschmied** [schwarzwaldgeier/meteo#39]
We can use OWM data for more than just nordost.  Add forecasts for the remaining day to the phone message right after the current message:

"Vorhersage für Vierzehn Uhr: Vier km/h aus  Nordost, klarer Himmel, ein Achtel Bewölkung."

Missing sound files can come from a synthesizer until we find a way / someone to record them.

Phone message only, radio is already a nuisance as it is.

**Comment by mxlian** [comment]
Nice one! I like it. I think it more suitable for the radio though. If you put it only on the phone: 'which problem are you trying to solve?'

**Comment by sebschmied** [comment]
The problem I had yesterday, I wanted to see if conditions will improve later but had poor internet.

**Comment by sebschmied** [comment]
Only phone: I think it would be annoying on the radio. You can hang up your phone anytime you want, but radio keeps blocking the frequency until done.
