### ISSUE TITLE
Make funk.wav remain silent when device is out of order

### ISSUE THREAD

**Issue by sebschmied** [schwarzwaldgeier/meteo#5]
When out of order, phone.wav should announce the problem, but funk.wav should remain silent (empty) instead of bugging pilots with a message every 5 minutes.

**Comment by mxlian** [comment]
Mmmm, idk. Have a couple arguments against it: 
- I think a short message indicating that the station is unable to retrieve current values could be helpful to know that your radio link is still working. The message can be very short, even a beep (but won't be as intuitive for those not familiar with it)
- Having the same behaviour on both (phone & radio) is more consistent and probably what any user would expect. 

What do you think?

**Comment by sebschmied** [comment]
You don't need a beep for testing your radio link, just ask another pilot to broadcast "testing testing" on that frequency.

I think phone and radio sound files don't need to be the same. When you call the station, you do so on purpose and expect a verbose analysis of wind and device status. Radio however broadcasts every 5 minutes on a public LPD frequency and interferes with vario beeps and pilot chatter. So, if the station doesn't have anything useful to say, it should remain silent.

The current behaviour is even more broken: The station keeps announcing old wind data, pilots are either fooled by that, or switch their radios off entirely.

**Comment by mxlian** [comment]
I meant the radio link with the station, if you don't hear anything the station can be ok but the radio TX can be the problem and you can't tell. The station telling you that information is temporary unavailable is useful information.

But anyways that's a fine detail. I think we both agree that if the data is not current anymore this data shouldn't be broadcasted. Let's do that.

For the rest it may be possible to make a poll to see what pilots prefer, in the case we want to decide the features more democratically. But let's leave that for the future... it's premature optimization

**Comment by mxlian** [comment]
@sebschmied here? https://github.com/schwarzwaldgeier/meteo/blob/master/BERGSTATION/GenerateSounds_neu.pl#L314

**Comment by sebschmied** [comment]
Thanks! Working on it

**Comment by sebschmied** [comment]
According to Timm "broadcast nothing at all" was the originally intended solution if there is no up-to-date data, I'm implementing it this way for now.
