### ISSUE TITLE
Audio generation and playback decoupled

### ISSUE THREAD

**Issue by mxlian** [schwarzwaldgeier/meteo#6]
The audio generation is an independent process from audio playback. 

@sebschmied suggested to get rid of the timestamps in the audio file for the radio (funk) which is kind of annoying. This introduces the danger that if the audio generation fails for some reason, the same audio file will be played over and over again without anyone noticing it.

To fix that, the same routine that generates the audio should play it or handle the error/exception (maybe playing another audio file, see discussion on issue #5)

**Comment by sebschmied** [comment]
Any idea how playback is currently handled? I see a cronjob for audio creation, but nothing for playback.

**Comment by mxlian** [comment]
Are you sure you are seeing the right crontab? Is in the system crontab (not user crontab):

```
....
# Wetterstation, Kind schlaeft von 21-9 Uhr
# Berechnung lauft durch fuer Telefon
0,5,10,15,20,25,30,35,40,45,50,55 *    * * * root /var/www/BERGSTATION/GenerateSounds_neu.pl

# Sprachausgabe Funk, hier auskommentieren                                    <--- here
 1,6,11,16,21,26,31,36,41,46,51,56 9-20 * * * root /usr/bin/play /var/www/BERGSTATION/FUNK.wav

# Restart Service SOCKET
*/15 * * * * root /var/www/BERGSTATION/wetterstation_neu/./wetter_restart
```

**Comment by sebschmied** [comment]
You're right. I had checked root's crontab accidentally.

**Comment by mxlian** [comment]
i can take care of this issue
