### ISSUE TITLE
clear question of the current design

### ISSUE THREAD

**Issue by mxlian** [schwarzwaldgeier/meteo#9]
- What are the components connected or that interact to/with meteogeier?
- How does the RADIO transmision work? (more hardware related)
- How does the PHONE station work? SW/HW

... TBC

**Comment by mxlian** [comment]
@sebschmied can you organize it? no hurries, whenever you have time for it

**Comment by sebschmied** [comment]
ack

**Comment by mxlian** [comment]
@sebschmied as I remember Timm cleared the design w/ u per waap, right? Should we document it and close this issue?

**Comment by sebschmied** [comment]
> What are the components connected or that interact to/with meteogeier?

"Data is sent from the station with a TCP client via socket connection, wetter_socket"

> How does the RADIO transmision work? (more hardware related)

"Sound card plays an mp3 to a loudspeaker. A seperate radio device next to that box is set to "vox"." (This explains the poor sound quality.)

> How does the PHONE station work? SW/HW

"ELSA Modem".

Sorry for taking so long!

**Comment by mxlian** [comment]
To a loudspeaker, really? :DDD I see a very easy improvement here
